---
# tasks file for letsencrypt
- name: apt update
  apt:
    update_cache: yes

- name: Install Certbot
  apt:
    name: python3-certbot-nginx
    state: present
    update_cache: yes

- name: Obtain SSL certificates from Let's Encrypt
  command: certbot --nginx -d "{{ domain_name }}" --non-interactive --agree-tos --email admin@{{ domain_name }}
  register: certbot_result
  ignore_errors: yes

- name: Check if SSL certificates are already obtained
  stat:
    path: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
  register: ssl_cert_check

- name: Renew SSL certificates if they exist
  command: certbot renew
  when: ssl_cert_check.stat.exists
