global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['135.237.120.226:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['135.237.120.226:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Choose the appropriate module
    static_configs:
      - targets:
          - http://135.237.120.226:80/api/v1/  # Target you want to probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: blackbox_exporter
      - target_label: __address__
        replacement: blackbox_exporter:9115
