scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Choose the appropriate module
    static_configs:
      - targets:
          - http://135.237.120.226/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: blackbox_exporter
      - target_label: __address__
        replacement: blackbox_exporter:9115
